#include <tchar.h>
#include "escr.h"


//#ifdef MODE
OPRLIST EventOprList[] = {
/*EventOprList_Start*/
//簡易関数
	{	_T("B"),					ESC_B			},	//
	{	_T("BT"),					ESC_BT			},	//
	{	_T("BC"),					ESC_BC			},	//
	{	_T("BCT"),					ESC_BCT			},	//
	{	_T("BD"),					ESC_BD			},	//
	{	_T("BR"),					ESC_BR			},	//
	{	_T("BF"),					ESC_BF			},	//
	{	_T("V"),					ESC_V			},	//
	{	_T("H"),					ESC_H			},	//
	{	_T("S"),					ESC_S			},	//
	{	_T("Z"),					ESC_Z			},	//
	{	_T("FI"),					ESC_FI			},	//
	{	_T("FIF"),					ESC_FIF			},	//
	{	_T("FO"),					ESC_FO			},	//
	{	_T("FOF"),					ESC_FOF			},	//
	{	_T("FB"),					ESC_FB			},	//
	{	_T("PFI"),					ESC_PFI			},	//
	{	_T("PFO"),					ESC_PFO			},	//
	{	_T("PWI"),					ESC_PWI			},	//
	{	_T("PWO"),					ESC_PWO			},	//
	{	_T("Q"),					ESC_Q			},	//
	{	_T("F"),					ESC_F			},	//
	{	_T("C"),					ESC_C			},	//
	{	_T("CR"),					ESC_CR			},	//
	{	_T("CP"),					ESC_CP			},	//
	{	_T("CL"),					ESC_CL			},	//
	{	_T("CY"),					ESC_CY			},	//
	{	_T("CB"),					ESC_CB			},	//
	{	_T("CA"),					ESC_CA			},	//
	{	_T("CW"),					ESC_CW			},	//
	{	_T("CRW"),					ESC_CRW			},	//
	{	_T("W"),					ESC_W			},	//
	{	_T("WR"),					ESC_WR			},	//
	{	_T("KW"),					ESC_KW			},	//
	{	_T("K"),					ESC_K			},	//
	{	_T("M"),					ESC_M			},	//
	{	_T("MS"),					ESC_MS			},	//
	{	_T("MP"),					ESC_MP			},	//
	{	_T("MV"),					ESC_MV			},	//
	{	_T("MW"),					ESC_MW			},	//
	{	_T("SE"),					ESC_SE			},	//
	{	_T("SEP"),					ESC_SEP			},	//
	{	_T("SES"),					ESC_SES			},	//
	{	_T("SEW"),					ESC_SEW			},	//
	{	_T("SEV"),					ESC_SEV			},	//
	{	_T("SEVW"),					ESC_SEVW		},	//
	{	_T("SetVolumeVoiceChar"),	ESC_SETVOLUMEVOICECHAR	},
	{	_T("SetVolumeVoiceScript"),	ESC_SETVOLUMEVOICESCRIPT	},
	{	_T("SV"),					ESC_SV			},	//
	{	_T("SVEX"),					ESC_SVEX		},	//
	{	_T("VV"),					ESC_VV			},	//
	{	_T("VA"),					ESC_VA			},	//
	{	_T("VB"),					ESC_VB			},	//
	{	_T("VC"),					ESC_VC			},	//
	{	_T("VX"),					ESC_VX			},	//
	{	_T("VW"),					ESC_VW			},	//
	{	_T("VS"),					ESC_VS			},	//
	{	_T("VI"),					ESC_VI			},	//
	{	_T("R"),					ESC_R			},	//
	{	_T("RC"),					ESC_RC			},	//
	{	_T("RR"),					ESC_RR			},	//
	{	_T("LF"),					ESC_LF			},	//
	{	_T("WE"),					ESC_WE			},	//
	{	_T("WER"),					ESC_WER			},	//
//低レベル関数
	{	_T("SetFlag"),				ESC_SETFLAG			},	//
	{	_T("GetFlag"),				ESC_GETFLAG			},	//
	{	_T("SetGameFlag"),			ESC_SETGAMEFLAG		},	//
	{	_T("GetGameFlag"),			ESC_GETGAMEFLAG		},	//
	{	_T("LoadScript"),			ESC_LOADSCRIPT		},	//
	{	_T("GameEnd"),				ESC_GAMEEND			},	//
	{	_T("CallFunc"),				ESC_CALLFUNC		},	//
	{	_T("ViewClock"),			ESC_VIEWCLOCK		},	//
	{	_T("SetWeatherMode"),		ESC_SETWEATHERMODE	},	//
	{	_T("SetTimeMode"),			ESC_SETTIMEMODE		},	//
	{	_T("SetTimeBack"),			ESC_SETTIMEBACK		},	//
	{	_T("SetTimeChar"),			ESC_SETTIMECHAR		},	//
	{	_T("SetMatrix"),			ESC_SETMATRIX		},	//
	{	_T("ShowChipBack"),			ESC_SHOWCHIPBACK	},	//
	{	_T("PoseChipBack"),			ESC_POSECHIPBACK	},	//
	{	_T("PlayChipBack"),			ESC_PLAYCHIPBACK	},	//
	{	_T("SetChipBack"),			ESC_SETCHIPBACK		},	//
	{	_T("SetChipParts"),			ESC_SETCHIPPARTS	},	//
	{	_T("SetChipScroll"),		ESC_SETCHIPSCROLL	},	//
	{	_T("SetChipScroll2"),		ESC_SETCHIPSCROLL2	},	//
	{	_T("SetChipScrollSpeed"),	ESC_SETCHIPSCROLLSPEED	},	//
	{	_T("WaitChipScroll"),		ESC_WAITCHIPSCROLL		},	//
	{	_T("WaitChipScrollSpeed"),	ESC_WAITCHIPSCROLLSPEED	},	//
	{	_T("SetChipCharCash"),		ESC_SETCHIPCHARCASH		},	//
	{	_T("ResetChipCharCash"),	ESC_RESETCHIPCHARCASH	},	//
	{	_T("SetChipChar"),			ESC_SETCHIPCHAR			},	//
	{	_T("SetChipCharAni"),		ESC_SETCHIPCHARANI		},	//
	{	_T("ResetChipChar"),		ESC_RESETCHIPCHAR		},	//
	{	_T("SetChipCharParam"),		ESC_SETCHIPCHARPARAM	},	//
	{	_T("SetChipCharBright"),	ESC_SETCHIPCHARBRIGHT	},	//
	{	_T("SetChipCharMove"),		ESC_SETCHIPCHARMOVE		},	//
	{	_T("SetChipCharMove2"),		ESC_SETCHIPCHARMOVE2	},	//
	{	_T("SetChipCharMoveSpeed"),	ESC_SETCHIPCHARMOVESPEED},	//
	{	_T("GetChipCharMove"),		ESC_GETCHIPCHARMOVE		},	//
	{	_T("GetChipCharMoveSpeed"),	ESC_GETCHIPCHARMOVESPEED},	//
	{	_T("CopyChipCharPos"),		ESC_COPYCHIPCHARPOS		},	//
	{	_T("SetChipCharRev"),		ESC_SETCHIPCHARREV		},	//
	{	_T("ThroughChipCharAni"),	ESC_THROUGHCHIPCHARANI	},	//
	{	_T("WaitChipCharRepeat"),	ESC_WAITCHIPCHARREPEAT	},	//
	{	_T("WaitChipCharAni"),		ESC_WAITCHIPCHARANI		},	//
	{	_T("WaitChipCharAniLoop"),	ESC_WAITCHIPCHARANILOOP	},	//
	{	_T("WaitChipCharMove"),		ESC_WAITCHIPCHARAMOVE	},	//
	{	_T("GetBack"),				ESC_GETBACK			},	//
	{	_T("SetBack"),				ESC_SETBACK			},	//
	{	_T("SetBack2"),				ESC_SETBACK2		},	//
	{	_T("SetCg"),				ESC_SETCG			},	//
	{	_T("SetCg2"),				ESC_SETCG2			},	//
	{	_T("SetBackPos"),			ESC_SETBACKPOS		},	//
	{	_T("SetBackPosZ"),			ESC_SETBACKPOSZ		},	//
	{	_T("SetBackScroll"),		ESC_SETBACKSCROLL	},	//
	{	_T("SetBackScrollZ"),		ESC_SETBACKSCROLLZ	},	//
	{	_T("SetBackCScope"),		ESC_SETBACKCSCOPE	},	//
	{	_T("WaitBackCScope"),		ESC_WAITBACKCSCOPE	},	//
	{	_T("LockBackCScope"),		ESC_LOCKBACKCSCOPE	},	//
	{	_T("SetBackFadeIn"),		ESC_SETBACKFADEIN	},	//
	{	_T("SetBackFadeOut"),		ESC_SETBACKFADEOUT	},	//
	{	_T("SetBackFadeRGB"),		ESC_SETBACKFADERGB	},	//
	{	_T("SetShake"),				ESC_SETSHAKE		},	//
	{	_T("StopShake"),			ESC_STOPSHAKE		},	//
	{	_T("SetFlash"),				ESC_SETFLASH		},	//
	{	_T("SetChar"),				ESC_SETCHAR			},	//
	{	_T("ResetChar"),			ESC_RESETCHAR		},	//
	{	_T("SetCharPose"),			ESC_SETCHARPOSE		},	//
	{	_T("SetCharLocate"),		ESC_SETCHARLOCATE	},	//
	{	_T("SetCharLayer"),			ESC_SETCHARLAYER	},	//
	{	_T("WaitChar"),				ESC_WAITCHAR		},	//
	{	_T("SetBlock"),				ESC_SETBLOCK		},	//
	{	_T("SetWindow"),			ESC_SETWINDOW		},	//
	{	_T("ResetWindow"),			ESC_RESETWINDOW		},	//
	{	_T("SetMessage"),			ESC_SETMESSAGE		},	//
	{	_T("SetMessage2"),			ESC_SETMESSAGE2		},	//
	{	_T("SetMessageEx"),			ESC_SETMESSAGEEX	},	//
	{	_T("SetChipMessage"),		ESC_SETCHIPMESSAGE	},	//
	{	_T("AddMessage"),			ESC_ADDMESSAGE		},	//
	{	_T("AddMessage2"),			ESC_ADDMESSAGE2		},	//
	{	_T("SetMessageWait"),		ESC_SETMESSAGEWAIT	},	//
	{	_T("ResetMessage"),			ESC_RESETMESSAGE	},	//
	{	_T("WaitKey"),				ESC_WAITKEY			},	//
	{	_T("SetSelectMes"),			ESC_SETSELECTMES	},	//
	{	_T("SetSelectMesEx"),		ESC_SETSELECTMESEX	},	//
	{	_T("SetSelect"),			ESC_SETSELECT		},	//
	{	_T("SetSelectEx"),			ESC_SETSELECTEX		},	//
	{	_T("PlayBgm"),				ESC_PLAYBGM			},	//
	{	_T("PlayBgmEx"),			ESC_PLAYBGMEX		},	//
	{	_T("StopBgm"),				ESC_STOPBGM			},	//
	{	_T("StopBgmEx"),			ESC_STOPBGMEX		},	//
	{	_T("SetVolumeBgm"),			ESC_SETVOLUMEBGM	},	//
	{	_T("SetVolumeBgmEx"),		ESC_SETVOLUMEBGMEX	},	//
	{	_T("PlaySe"),				ESC_PLAYSE			},	//
	{	_T("PlaySeEx"),				ESC_PLAYSEEX		},	//
	{	_T("StopSeEx"),				ESC_STOPSEEX		},	//
	{	_T("SetVolumeSe"),			ESC_SETVOLUMESE		},	//
	{	_T("SetWeather"),			ESC_SETWEATHER		},	//
	{	_T("ChangeWeather"),		ESC_CHANGEWEATHER	},	//
	{	_T("ResetWeather"),			ESC_RESETWEATHER	},	//
	{	_T("SetLensFrea"),			ESC_SETLENSFREA		},	//
	{	_T("SetWavEffect"),			ESC_SETWAVEFFECT	},	//
	{	_T("ResetWavEffect"),		ESC_RESETWAVEFFECT	},	//
	{	_T("SetWarp"),				ESC_SETWARP			},	//
	{	_T("ResetWarp"),			ESC_RESETWARP		},	//
	{	_T("WaitFrame"),			ESC_WAITFRAME		},	//
	{	_T("SetBmp"),				ESC_SETBMP			},	//
	{	_T("SetBmpEx"),				ESC_SETBMPEX		},	//
	{	_T("SetBmp4Bmp"),			ESC_SETBMP4BMP		},	//
	{	_T("SetBmpPrim"),			ESC_SETBMPPRIM		},	//
	{	_T("ResetBmp"),				ESC_RESETBMP		},	//
	{	_T("ResetBmpAll"),			ESC_RESETBMPALL		},	//
	{	_T("SetBmpAnime"),			ESC_SETBMPANIME		},	//
	{	_T("ResetBmpAnime"),		ESC_RESETBMPANIME	},	//
	{	_T("WaitBmpAnime"),			ESC_WAITBMPANIME	},	//
	{	_T("SetTitle"),				ESC_SETTITLE		},	//
	{	_T("SetEnding"),			ESC_SETENDING		},	//
	{	_T("SetOpening"),			ESC_SETOPENING		},	//
	{	_T("SetAvi"),				ESC_SETAVI			},	//
	{	_T("ResetAvi"),				ESC_RESETAVI		},	//
	{	_T("WaitAvi"),				ESC_WAITAVI			},	//
	{	_T("SetAviFull"),			ESC_SETAVIFULL		},	//
	{	_T("WaitAviFull"),			ESC_WAITAVIFULL		},	//
	{	_T("SetBmpDisp"),			ESC_SETBMPDISP		},	//
	{	_T("SetBmpLayer"),			ESC_SETBMPLAYER		},	//
	{	_T("SetBmpParam"),			ESC_SETBMPPARAM		},	//
	{	_T("SetBmpRevParam"),		ESC_SETBMPREVPARAM	},	//
	{	_T("SetBmpBright"),			ESC_SETBMPBRIGHT	},	//
	{	_T("SetBmpMove"),			ESC_SETBMPMOVE		},	//
	{	_T("SetBmpPos"),			ESC_SETBMPPOS		},	//
	{	_T("SetBmpZoom"),			ESC_SETBMPZOOM		},	//
	{	_T("SetBmpZoom2"),			ESC_SETBMPZOOM2		},	//
	{	_T("SetDemoFlag"),			ESC_SETDEMOFLAG		},	//
	{	_T("SetSceneNo"),			ESC_SETSCENENO		},	//
	{	_T("SetEndingNo"),			ESC_SETENDINGNO		},	//
	{	_T("SetReplayNo"),			ESC_SETREPLAYNO		},	//
	{	_T("SetSoundEvent"),		ESC_SETSOUNDEVENT	},	//
	{	_T("SetSoundEventVolume"),	ESC_SETSOUNDEVENTVOLUME	},	//
	{	_T("SetPotaPota"),			ESC_SETPOTAPOTA		},	//
	{	_T("GetTime"),				ESC_GETTIME			},	//
	{	_T("WaitTime"),				ESC_WAITTIME		},	//
	{	_T("SetTextFormat"),		ESC_SETTEXTFORMAT	},	//
	{	_T("SetTextSync"),			ESC_SETTEXTSYNC		},	//		
	{	_T("SetText"),				ESC_SETTEXT			},	//
	{	_T("SetTextEx"),			ESC_SETTEXTEX		},	//
	{	_T("ResetText"),			ESC_RESETTEXT		},	//
	{	_T("WaitText"),				ESC_WAITTEXT		},	//
	{	_T("ResetTextAll"),			ESC_RESETTEXTALL	},	//
	{	_T("SetDemoFadeFlag"),		ESC_SETDEMOFADEFLAG	},	//
	{	_T("Mov2"),					ESC_MOV2			},	//
	{	_T("Sin"),					ESC_SIN				},	//
	{	_T("Cos"),					ESC_COS				},	//
	{	_T("Abs"),					ESC_ABS				},	//
	{	_T("SetCutCut"),			ESC_SETCUTCUT		},	//
	{	_T("SetNoise"),				ESC_SETNOISE		},	//
	{	_T("T"),					ESC_T				},	//
	{	_T("SetUsoErr"),			ESC_SETUSOERR		},	//
	{	_T("LoadScriptNum"),		ESC_LOADSCRIPTNUM	},	//
	{	_T("SetRipple"),			ESC_SETRIPPLE		},	//
	{	_T("SetRippleSet"),			ESC_SETRIPPLESET	},	//
	{	_T("WaitRipple"),			ESC_WAITRIPPLE		},	//
	{	_T("SetRippleLost"),		ESC_SETRIPPLELOST	},	//
	{	_T("MLW"),					ESC_MLW				},	//
	{	_T("VT"),					ESC_VT				},	//
	{	_T("HT"),					ESC_HT				},	//
	{	_T("SetMapEvent"),			ESC_SETMAPEVENT		},	//
	{	_T("VIB"),					ESC_VIB				},	//
	{	_T("ViewCalender"),			ESC_VIEWCALENDER	},	//
	{	_T("SetSakura"),			ESC_SETSAKURA		},
	{	_T("StopSakura"),			ESC_STOPSAKURA		},
	{	_T("SkipDate"),				ESC_SKIPDATE		},
	{	_T("SetMovie"),				ESC_SETMOVIE		},	//
	{	_T("DebugBox"),				ESC_DEBUGBOX		},	//
	{	_T("VHFlag"),				ESC_VHFLAG			},	//
	{	_T("GetSystemTime"),		ESC_GETSYSTEMTIME	},	//
	{	NULL,					ESC_OPR_MAX			},
};
//#endif//MODE

ESCRIPT_OPR		EScroptOpr[] = {
/*EScroptOpr_Start*/
	{//	ESC_B
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 5
	},
	{//	ESC_BT
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 5
	},
	{//	ESC_BC
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 5
	},
	{//	ESC_BCT
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 5
	},
	{//	ESC_BD
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_BR
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 2
	},
	{//	ESC_BF
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 2
	},
	{//	ESC_V
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 6
	},
	{//	ESC_H
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 6
	},

	{//	ESC_S
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_Z
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_FI
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_FIF
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_FO
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_FOF
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_FB
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_PFI
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 2
	},
	{//	ESC_PFO
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 2
	},
	{//	ESC_PWI
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 2
	},
	{//	ESC_PWO
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 2
	},

	{//	ESC_Q
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_F
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},

	{//	ESC_C
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 6
	},
	{//	ESC_CR
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 2
	},
	{//	ESC_CP
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 1
	},
	{//	ESC_CL
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 1
	},
	{//	ESC_CY
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_CB
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_CA
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_CW
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 4
	},
	{//	ESC_CRW
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 1
	},

	{//	ESC_W
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 1
	},
	{//	ESC_WR
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 1
	},

	{//	ESC_KW
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_K
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
	 	 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},

	{//	ESC_M
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 3
	},
	{//	ESC_MS
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 1
	},
	{//	ESC_MP
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_MV
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_MW
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},

	{//	ESC_SE
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 1
	},
	{//	ESC_SEP
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 3
	},
	{//	ESC_SES
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 1
	},
	{//	ESC_SEW
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_SEV
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SEVW
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	
	{//	ESC_SETVOLUMEVOICECHAR
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETVOLUMEVOICESCRIPT
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},

	{//	ESC_SV
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_VCNT, ESC_NUM,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 5
	},
	{//	ESC_SVEX
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 5
	},

	{//	ESC_VV
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_VCNT, ESC_NUM,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 4
	},
	{//	ESC_VA
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_VCNT, ESC_NUM,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 4
	},
	{//	ESC_VB
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_VCNT, ESC_NUM,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 4
	},
	{//	ESC_VC
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_VCNT, ESC_NUM,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 4
	},

	{//	ESC_VX
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 3
	},
	{//	ESC_VW
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 1
	},
	{//	ESC_VS
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 1
	},
	{//	ESC_VI
		{ESC_VCNT, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 3
	},
	{//	ESC_R
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_RC
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_RR
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_LF
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_WE
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 1
	},
	{//	ESC_WER
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},

	{//	ESC_SETFLAG
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_GETFLAG
		{ESC_NUM, ESC_REG, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},

	{//ESC_SETGAMEFLAG
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//ESC_GETGAMEFLAG
		{ESC_NUM, ESC_REG, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_LOADSCRIPT
		{ESC_STR, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_GAMEEND
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 1
	},
	{//	ESC_CALLFUNC
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM},
		ESC_NOWAIT, 14
	},
	{//	ESC_VIEWCLOCK
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 2
	},
	{//	ESC_SETWEATHERMODE
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 1
	},
	{//	ESC_SETTIMEMODE
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 2
	},
	{//	ESC_SETTIMEBACK
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 2
	},
	{//	ESC_SETTIMECHAR
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 2
	},
//背景関連
	{//	ESC_SETMATRIX
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SHOWCHIPBACK
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 2
	},
	{//	ESC_POSECHIPBACK
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_PLAYCHIPBACK
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETCHIPBACK
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETCHIPPARTS
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 2
	},
	{//	ESC_SETCHIPSCROLL
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETCHIPSCROLL2
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETCHIPSCROLLSPEED
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_WAITCHIPSCROLL
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_WAITCHIPSCROLLSPEED
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_SETCHIPCHARCASH,
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_RESETCHIPCHARCASH,
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETCHIPCHAR,
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETCHIPCHARANI,
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_RESETCHIPCHAR,
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETCHIPCHARPARAM
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETCHIPCHARBRIGHT
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETCHIPCHARMOVE,
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETCHIPCHARMOVE2,
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETCHIPCHARMOVESPEED,
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_GETCHIPCHARMOVE,
		{ESC_NUM, ESC_REG, ESC_REG, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_GETCHIPCHARMOVESPEED,
		{ESC_NUM, ESC_REG, ESC_REG, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//ESC_COPYCHIPCHARPOS
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETCHIPCHARREV,
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_THROUGHCHIPCHARANI,
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_WAITCHIPCHARREPEAT,
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 1
	},
	{//	ESC_WAITCHIPCHARANI,
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 1
	},
	{//	ESC_WAITCHIPCHARANILOOP,
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 1
	},
	{//	ESC_WAITCHIPCHARAMOVE,
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_GETBACK
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_SETBACK
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_SETBACK2
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_SETCG
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_SETCG2
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_SETBACKPOS
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETBACKPOSZ
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETBACKSCROLL
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_SETBACKSCROLLZ
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_SETBACKCSCOPE
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_WAITBACKCSCOPE
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_LOCKBACKCSCOPE
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},

	{//	ESC_SETBACKFADEIN
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 1
	},
	{//	ESC_SETBACKFADEOUT
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 1
	},
	{//	ESC_SETBACKFADERGB
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 1
	},
	{//	ESC_SETSHAKE
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 1
	},
	{//	ESC_STOPSHAKE
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_SETFLASH
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
//人物関連
	{//	ESC_SETCHAR
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 6
	},
	{//	ESC_RESETCHAR
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 2
	},
	{//	ESC_SETCHARPOSE
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETCHARLOCATE
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETCHARLAYER
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_WAIT, 0CHAR
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
//Window関連
	{//	ESC_SETBLOCK
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETWINDOW
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 1
	},
	{//	ESC_RESETWINDOW
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 1
	},
	{//	ESC_SETMESSAGE
		{ESC_NUM, ESC_STR, ESC_CNT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_SETMESSAGE2
		{ESC_STR2,ESC_ADD, ESC_CNT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_SETMESSAGEEX
		{ESC_NUM, ESC_NUM, ESC_STR, ESC_NUM, ESC_CNT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_SETCHIPMESSAGE
		{ESC_STR, ESC_CNT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_ADDMESSAGE
		{ESC_NUM, ESC_STR, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_ADDMESSAGE2
		{ESC_STR2,ESC_ADD, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_SETMESSAGEWAIT, 0
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_RESETMESSAGE
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_WAIT, 0KEY
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_SETSELECTMESSAGE
		{ESC_STR, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 3
	},
	{//	ESC_SETSELECTMESSAGEEX
		{ESC_STR, ESC_STR, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 2
	},
	{//	ESC_SETSELECT
		{ESC_REG, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_SETSELECTEX
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
//サウンド関連
	{//	ESC_PLAYBGM
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_PLAYBGMEX
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_STOPBGM
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_STOPBGMEX
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETVOLUMEBGM
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETVOLUMEBGMEX
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_PLAYSE
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_PLAYSEEX
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_STOPSEEX
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETVOLUMESE
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
//その他
	{//	ESC_SETWEATHER
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_CHANGEWEATHER
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_RESETWEATHER
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_SETLENSFREA
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETWAVEFFECT
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 3
	},
	{//	ESC_RESETWAVEFFECT
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},

	{//	ESC_SETWARP
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 8
	},
	{//	ESC_RESETWARP
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 1
	},
	{//	ESC_WAIT, 0FRAME
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_SETBMP
		{ESC_NUM, ESC_NUM, ESC_STR, ESC_NUM, ESC_NUM,
		 ESC_STR, ESC_NUM, ESC_NUM, ESC_STR, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 4
	},
	{//	ESC_SETBMPEX
		{ESC_NUM, ESC_NUM, ESC_STR, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_STR, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 2
	},
	{//	ESC_SETBMP4BMP
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//ESC_SETBMPPRIM
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_RESETBMP
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_RESETBMPALL
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETBMPANIME
		{ESC_NUM, ESC_STR, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 3
	},
	{//	ESC_RESETBMPANIME
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_WAITBMPANIME
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_SETTITLE
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_SETENDING
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_SETOPENING
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_SETAVI,
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_STR,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_RESETAVI,
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_WAITAVI,
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_SETAVIFULL,
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_WAITAVIFULL,
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_SETBMPDISP
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETBMPLAYER
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETBMPPARAM
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 1
	},
	{//	ESC_SETBMPREVPARAM
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETBMPBRIGHT
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 2
	},
	{//	ESC_SETBMPMOVE
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETBMPPOS
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETBMPZOOM
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETBMPZOOM2
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETDEMOFLAG
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETSCENENO
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETENDINGNO
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETREPLAYNO
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	
	{//	ESC_SETSOUNDEVENT
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 5
	},
	{//	ESC_SETSOUNDEVENTVOLUME
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 2
	},
	{//	ESC_SETPOTAPOTA
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 3
	},
	{//	ESC_GETTIME
		{ESC_REG, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_WAITTIME
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_SETTEXTFORMAT
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 10
	},
	{//	ESC_SETTEXTSYNC
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETTEXT
		{ESC_NUM, ESC_STR, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_SETTEXTEX
		{ESC_STR, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_RESETTEXT
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_WAITTEXT
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_RESETTEXTALL
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETDEMOFADEFLAG
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_MOV2
		{ESC_REG, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SIN
		{ESC_REG, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 1
	},
	{//	ESC_COS
		{ESC_REG, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 1
	},
	{//	ESC_ABS
		{ESC_REG, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETCUTCUT
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETNOISE
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 2
	},
	{//	ESC_T
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 1
	},
	{//	ESC_SETUSOERR
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_LOADSCRIPTNUM
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_SETRIPPLE
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETRIPPLESET
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 1
	},
	{//	ESC_WAITRIPPLE
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_SETRIPPLELOST
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_MLW
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_VT
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 6
	},
	{//	ESC_HT
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 6
	},
	{//	ESC_SETMAPEVENT
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_STR, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_VIB
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_VIEWCALENDER
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 2
	},
	{//	ESC_SETSAKURA
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_STOPSAKURA
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_SKIPDATE
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},

	{//	ESC_SETMOVIE
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_DEBUGBOX
		{ESC_NUM, ESC_STR, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 1
	},
	{//	ESC_VHFLAG
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_GETSYSTEMTIME
		{ESC_REG, ESC_REG, ESC_REG, ESC_REG, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
};
